//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTAutoMusic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YTAutoMusic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------
        ///YTMusicDownloader:
        ///---------------------
        ///&apos;n&apos; - new playlist
        ///Create new playlist from a YouTube playlist. Place files in a new folder.
        ///---------------------
        ///&apos;a&apos; - append playlist
        ///Update a playlist to include new music from YouTube playlist. Requires an existing playlist folder with a &apos;tracks&apos; folder inside
        ///---------------------.
        /// </summary>
        internal static string helpText {
            get {
                return ResourceManager.GetString("helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  __     _________            _        _____                      _                 _           
        /// \ \   / /__   __|/\        | |      |  __ \                    | |               | |          
        ///  \ \_/ /   | |  /  \  _   _| |_ ___ | |  | | _____      ___ __ | | ___   __ _  __| | ___ _ __ 
        ///   \   /    | | / /\ \| | | | __/ _ \| |  | |/ _ \ \ /\ / / &apos;_ \| |/ _ \ / _` |/ _` |/ _ \ &apos;__|
        ///    | |     | |/ ____ \ |_| | || (_) | |__| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   
        ///    |_|     |_/_/    \_\__, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string splash {
            get {
                return ResourceManager.GetString("splash", resourceCulture);
            }
        }
    }
}
