using YTAutoMusic.Metadata_Fillers;

namespace YTAutoMusicTests.Metadata_Filler_Tests
{
    /// <summary>
    /// Test <see cref="ProvidedMetadata"/>
    /// </summary>
    public class ProvidedByYTTests
    {
        /*
         * Provided to YouTube by INSERTCOMPANYHERE
         * 
         * Title · Artist
         * 
         * Album
         * 
         * ℗
         * 
         * Released on: YYYY-MM-DD
         * 
         * ...
         * 
         * Auto-generated by YouTube.
         */

        [Fact]
        public void Basic()
        {
            var tagFile = TagFileCreater.CreateTemp();
            var data = new ProvidedMetadata();

            string title = "Title";
            string description = "Provided to YouTube by INSERTCOMPANYHERE\r\n\r\nTitle · Artist\r\n\r\nAlbum\r\n\r\n℗\r\n\r\nReleased on: 1234-10-05\r\n\r\n...\r\n\r\nAuto-generated by YouTube.";
            
            Assert.True(data.Fill(tagFile, title, description));

            Assert.Equal("Title", tagFile.Tag.Title);
            Assert.Equal("Artist", tagFile.Tag.Performers[0]);
            Assert.Equal("Album", tagFile.Tag.Album);
            Assert.Equal(1234u, tagFile.Tag.Year);
        }
    }
}
